apiVersion: v1
kind: Service
metadata:
  name: cosign-gatekeeper-provider
  namespace: gatekeeper-system
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    run: cosign-gatekeeper-provider
  sessionAffinity: None
